Pet.create!(description: "Cachorro preto encontrado perto da praça central", address: "Rua A, São Paulo", found_at: Date.today - 2.days, species: "Dog")
Pet.create!(description: "Gato branco com manchas pretas visto no quintal", address: "Rua B, São Paulo", found_at: Date.today - 4.days, species: "Cat")
Pet.create!(description: "Peixe dourado resgatado de um aquário abandonado", address: "Rua C, São Paulo", found_at: Date.today - 7.days, species: "Fish")
Pet.create!(description: "Cavalo marrom perambulando pela estrada", address: "Estrada D, São Paulo", found_at: Date.today - 10.days, species: "Horse")
Pet.create!(description: "Tartaruga pequena encontrada em um jardim", address: "Rua E, São Paulo", found_at: Date.today - 6.days, species: "Turtle")
Pet.create!(description: "Cachorro salsicha perdido na calçada", address: "Rua F, São Paulo", found_at: Date.today - 1.day, species: "Dog")
Pet.create!(description: "Gato preto encontrado dentro da garagem", address: "Rua G, São Paulo", found_at: Date.today - 3.days, species: "Cat")
Pet.create!(description: "Cavalo branco solto próximo ao parque", address: "Rua H, São Paulo", found_at: Date.today - 8.days, species: "Horse")
Pet.create!(description: "Tartaruga média achada em terreno baldio", address: "Rua I, São Paulo", found_at: Date.today - 5.days, species: "Turtle")
Pet.create!(description: "Cachorro labrador visto na praça", address: "Rua J, São Paulo", found_at: Date.today - 12.days, species: "Dog")
Pet.create!(description: "Peixe beta encontrado em caixa d'água", address: "Rua K, São Paulo", found_at: Date.today - 2.days, species: "Fish")
Pet.create!(description: "Gato siamês encontrado próximo ao mercado", address: "Rua L, São Paulo", found_at: Date.today - 9.days, species: "Cat")
Pet.create!(description: "Cavalo pônei visto solto na rua", address: "Rua M, São Paulo", found_at: Date.today - 11.days, species: "Horse")
Pet.create!(description: "Cachorro filhote vira-lata encontrado em praça", address: "Rua N, São Paulo", found_at: Date.today - 7.days, species: "Dog")
Pet.create!(description: "Tartaruga gigante encontrada em condomínio", address: "Rua O, São Paulo", found_at: Date.today - 15.days, species: "Turtle")
Pet.create!(description: "Gato persa visto no quintal vizinho", address: "Rua P, São Paulo", found_at: Date.today - 13.days, species: "Cat")
Pet.create!(description: "Cachorro poodle perdido no bairro", address: "Rua Q, São Paulo", found_at: Date.today - 14.days, species: "Dog")
